doctrine:
  dbal:
    types:
      geography:
        class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
        commented: false
      geometry:
        class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
        commented: false
      raster:
        class: 'Jsor\Doctrine\PostGIS\Types\RasterType'
        commented: false
      uuid:  'Ramsey\Uuid\Doctrine\UuidType'